site_name: pgraf
site_description: PostgreSQL-based property graph engine with vector search capabilities
site_author: Gavin M. Roy
site_url: https://github.com/gmr/pgraf

repo_name: gmr/pgraf
repo_url: https://github.com/gmr/pgraf
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [pgraf]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_bases: true
            heading_level: 2

nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference:
    - Graph: api/graph.md
    - Models: api/models.md
    - Embeddings: api/embeddings.md
    - Postgres: api/postgres.md
    - Queries: api/queries.md
    - Errors: api/errors.md
    - Utils: api/utils.md
  - Contributing: contributing.md
  - License: license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gmr/pgraf
      name: pgraf on GitHub
